### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by mitchellthomas10**
Replaced `req.params` with `req.body` in form data validation to read the proper variables

For issue #5

### CODE REVIEW

**Comment by jsdevel** [comment]
looks like tests are failing @mitchellthomas10.  Can you update them?

**Comment by mitchellthomas10** [comment]
I fixed the failing test. It was disabling the body parser, which left `req.body` null instead of just blank.

**Comment by Blackbaud-MitchellThomas** [comment]
Any ideas when this will be released?

**Comment by jsdevel** [comment]
Thanks for your patience @mitchellthomas10!  Published as `v0.9.0`.

**Pull request merged**
